name: Build changed Helm charts
description: Build any Helm charts that have been modified when compared to the master branch
inputs:
  target-branch:
      description: Git repository branch to check against when determining charts that have changed.
      required: true
      default: "master"
  unstable-build-suffix:
      description: |
        The unstable build suffix is appended to the chart version for unstable builds.
        If the unstable build suffix is the empty string, then a stable build is performed.
      required: false
      default: ""

runs:
  using: composite
  steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Setup helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.2
    - name: Setup chart-testing
      uses: helm/chart-testing-action@v2
      with:
        version: v3.4.0

    - name: Update chart-testing configuration with chart dirs
      shell: bash
      run: | 
        $GITHUB_ACTION_PATH/scripts/update-ct-config-with-chart-dirs.sh charts

    - name: Build changed Helm charts
      shell: bash
      run: | 
        $GITHUB_ACTION_PATH/scripts/build_changed_charts.sh ./charts ${{ inputs.target-branch }}
